USE [bbgdata]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].VIPNursingCard(
	CardID varchar(20)  NOT NULL PRIMARY KEY,
	Vip varchar(20)  NOT NULL FOREIGN KEY REFERENCES CustomerVIP(Vip)ON DELETE CASCADE ON UPDATE CASCADE,
	BegainDate [datetime]  NOT NULL,
	ExpireDate  [datetime]  NOT NULL,
)
GO

SET ANSI_PADDING OFF
GO