CREATE procedure WNBB_ZBHFX(
	@CESHI_TempTable varchar(1000),        -- 临时表
	@KHDaiMa  varchar(8000),               -- 客户代码
	@CKDaiMa  varchar(8000),               -- 仓库代码
	@StratDate  varchar(20),               -- 销售开始日期
	@EndDate  varchar(20),                 -- 销售结束日期
)
AS	
	-- 初始化状态
	if @KHDaiMa<>'' set @KHDaiMa=' and ' +@KHDaiMa; 
	if @CKDaiMa<>'' set @CKDaiMa=' and ' +@CKDaiMa;
	
	  
	
	--若临时表存在，则删除临时表
	if exists (select * from tempdb.dbo.sysobjects where  name =@CESHI_TempTable)                     
		Exec('Drop table '+@CESHI_TempTable)   
	
		
	-- @sqlstr保存SQL语句
	declare @sqlstr varchar(max);
	
	set @sqlstr= 'SELECT KC.SPDM, SHANGPIN.SPMC, GUIGE1.GGMC YANSE, GUIGE2.GGMC CHIMA
	, DALEI.DLMC DALEI, FJSX3.SXMC XIAOLEI, SHANGPIN.BYZD8 NIANFEN, JIJIE.JJMC JIJIE
	, PINPAI.PPMC PINPAI, FJSX1.SXMC KUANSHI, FJSX2.SXMC XINGBIE, FJSX4.SXMC XILIE
	, FJSX5.SXMC SHANGHUO, FJSX14.SXMC KUAIFAN, FJSX8.SXMC MIANLIAO , FJSX15.SXMC WAICAI
	, SHANGPIN.BZSJ JSJ, SHANGPIN.SJ3 DPJ, SHANGPIN.SJ4 ZYJ, SHANGPIN.CBJE CBJ
	, SPJH.SHRQ , SPJH.SHSL, YEARLS.LSSL, MONTHLS3.LSSL, MONTHLS2.LSSL, MONTHLS1.LSSL
	, LS.LSSL, LS.LSJE, (LS.LSJE-SHANGPIN.CBJE*LS.LSSL) ML
	, (CASE WHEN LS.LSJE<>0 THEN round((LS.LSJE-SHANGPIN.CBJE*LS.LSSL)/LS.LSJE,1) ELSE 0 END)  MLL
	, DPKC.KCSL, DPKC.KCZTSL, CKKC.KCSL, CKKC.KCZTSL
	, (CASE WHEN LS.LSSL<>0 THEN ((ISNULL(DPKC.KCSL,0)+ISNULL(DPKC.KCZTSL,0)+ISNULL(CKKC.KCSL,0)+ISNULL(CKKC.KCZTSL,0))/LS.LSSL) 
	ELSE ((ISNULL(DPKC.KCSL,0)+ISNULL(DPKC.KCZTSL,0)+ISNULL(CKKC.KCSL,0)+ISNULL(CKKC.KCZTSL,0))/1)  END)  ZZL
	, ''' + @StratDate + ''' as StratDate,'''+@EndDate+''' as EndDate 
	INTO ' + @CESHI_TempTable + '
	FROM (SELECT SPDM, GG1DM, GG2DM
		FROM SPKCB JOIN CANGKU ON SPKCB.CKDM = CANGKU.CKDM
		WHERE (SPKCB.SL<>0 OR SPKCB.SL2<>0) ' + @KHDaiMa + ' ' + @CKDaiMa + '
		GROUP BY SPDM, GG1DM, GG2DM
			) KC
		JOIN SHANGPIN ON SHANGPIN.SPDM = KC.SPDM
		JOIN DALEI ON DALEI.DLDM = SHANGPIN.BYZD4
		JOIN FJSX3 ON FJSX3.SXDM = SHANGPIN.FJSX3
		JOIN JIJIE ON JIJIE.JJDM = SHANGPIN.BYZD5
		JOIN PINPAI ON PINPAI.PPDM = SHANGPIN.BYZD3
		JOIN FJSX1 ON FJSX1.SXDM = SHANGPIN.FJSX1
		JOIN FJSX2 ON FJSX2.SXDM = SHANGPIN.FJSX2
		JOIN FJSX4 ON FJSX4.SXDM = SHANGPIN.FJSX4
		JOIN FJSX5 ON FJSX5.SXDM = SHANGPIN.FJSX5
		JOIN FJSX14 ON FJSX14.SXDM = SHANGPIN.FJSX14
		JOIN FJSX8 ON FJSX8.SXDM = SHANGPIN.FJSX8
		JOIN FJSX15 ON FJSX15.SXDM = SHANGPIN.FJSX15
		JOIN GUIGE1 ON GUIGE1.GGDM = KC.GG1DM
		JOIN GUIGE2 ON GUIGE2.GGDM = KC.GG2DM
		LEFT JOIN (
			SELECT MIN(SHRQ) SHRQ, SPDM, GG1DM, GG2DM, SUM(SPJHDMX.SL) SHSL
			FROM SPJHDMX JOIN SPJHD ON SPJHDMX.DJBH = SPJHD.DJBH 
			Group By  SPDM, GG1DM, GG2DM
		) SPJH ON SPJH.SPDM = KC.SPDM
			AND SPJH.GG1DM = KC.GG1DM 
			AND SPJH.GG2DM = KC.GG2DM 
		LEFT JOIN (select SPDM, GG1DM, GG2DM, SUM(SL) LSSL FROM(
			SELECT LSXHDMX.SPDM, LSXHDMX.GG1DM , LSXHDMX.GG2DM, LSXHDMX.SL
			from LSXHD JOIN LSXHDMX ON LSXHDMX.DJBH = LSXHD.DJBH
			WHERE  YS = '+1+' AND DATENAME(YYYY,GETDATE())=DATENAME(YYYY,SHRQ)
				AND LSXHD.DM1 = ' + @KHDaiMa  + ' 
			UNION ALL
			SELECT LSTHDMX.SPDM, LSTHDMX.GG1DM, LSTHDMX.GG2DM, LSTHDMX.SL * -1 SL
			FROM LSTHD JOIN LSTHDMX ON LSTHDMX.DJBH = LSTHD.DJBH
			WHERE  YS = '+1+' AND DATENAME(YYYY,GETDATE())=DATENAME(YYYY,SHRQ)
				AND LSTHD.DM1 = ' + @KHDaiMa  +' 
			) A
			GROUP BY SPDM,GG1DM,GG2DM
		) YEARLS ON KC.SPDM = YEARLS.SPDM
			AND KC.GG1DM = YEARLS.GG1DM 
			AND KC.GG2DM = YEARLS.GG2DM  
		LEFT JOIN (select SPDM, GG1DM, GG2DM, SUM(SL) LSSL FROM(
			SELECT LSXHDMX.SPDM, LSXHDMX.GG1DM , LSXHDMX.GG2DM, LSXHDMX.SL
			from LSXHD JOIN LSXHDMX ON LSXHDMX.DJBH = LSXHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-3,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-3,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSXHD.DM1 = ' + @KHDaiMa  + ' 
			UNION ALL
			SELECT LSTHDMX.SPDM, LSTHDMX.GG1DM, LSTHDMX.GG2DM, LSTHDMX.SL * -1 SL
			FROM LSTHD JOIN LSTHDMX ON LSTHDMX.DJBH = LSTHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-3,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-3,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSTHD.DM1 = ' + @KHDaiMa  + ' 
			) A
			GROUP BY SPDM,GG1DM,GG2DM
		) MONTHLS3 ON KC.SPDM = MONTHLS3.SPDM
			AND KC.GG1DM = MONTHLS3.GG1DM 
			AND KC.GG2DM = MONTHLS3.GG2DM  
		LEFT JOIN (select SPDM, GG1DM, GG2DM, SUM(SL) LSSL FROM(
			SELECT LSXHDMX.SPDM, LSXHDMX.GG1DM , LSXHDMX.GG2DM, LSXHDMX.SL
			from LSXHD JOIN LSXHDMX ON LSXHDMX.DJBH = LSXHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-2,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-2,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSXHD.DM1 = ' + @KHDaiMa  + ' 
			UNION ALL
			SELECT LSTHDMX.SPDM, LSTHDMX.GG1DM, LSTHDMX.GG2DM, LSTHDMX.SL * -1 SL
			FROM LSTHD JOIN LSTHDMX ON LSTHDMX.DJBH = LSTHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-2,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-2,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSTHD.DM1 = ' + @KHDaiMa  + ' 
			) A
			GROUP BY SPDM,GG1DM,GG2DM
		) MONTHLS2 ON KC.SPDM = MONTHLS2.SPDM
			AND KC.GG1DM = MONTHLS2.GG1DM 
			AND KC.GG2DM = MONTHLS2.GG2DM  
		LEFT JOIN (select SPDM, GG1DM, GG2DM, SUM(SL) LSSL FROM(
			SELECT LSXHDMX.SPDM, LSXHDMX.GG1DM , LSXHDMX.GG2DM, LSXHDMX.SL 
			from LSXHD JOIN LSXHDMX ON LSXHDMX.DJBH = LSXHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-1,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-1,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSXHD.DM1 = ' + @KHDaiMa  + ' 
			UNION ALL
			SELECT LSTHDMX.SPDM, LSTHDMX.GG1DM, LSTHDMX.GG2DM, LSTHDMX.SL * -1 SL
			FROM LSTHD JOIN LSTHDMX ON LSTHDMX.DJBH = LSTHD.DJBH
			WHERE  YS = '+1+' AND YEAR( DATEADD(MONTH,-1,GETDATE()))=DATENAME(YEAR,SHRQ)
				AND MONTH( DATEADD(MONTH,-1,GETDATE()))=DATENAME(MONTH,SHRQ)
				AND LSTHD.DM1 = ' + @KHDaiMa  + ' 
			) A
			GROUP BY SPDM,GG1DM,GG2DM
		) MONTHLS1 ON KC.SPDM = MONTHLS1.SPDM
			AND KC.GG1DM = MONTHLS1.GG1DM 
			AND KC.GG2DM = MONTHLS1.GG2DM  
		LEFT JOIN (select SPDM, GG1DM, GG2DM, SUM(SL) LSSL, SUM(JE) LSJE FROM(
			SELECT LSXHDMX.SPDM, LSXHDMX.GG1DM , LSXHDMX.GG2DM, LSXHDMX.JE
			, LSXHDMX.SL
			from LSXHD JOIN LSXHDMX ON LSXHDMX.DJBH = LSXHD.DJBH
			WHERE  YS = '+1+' AND ' + @StratDate + ' AND ' + @EndDate + ' 
				AND LSXHD.DM1 =' + @KHDaiMa  + ' 
			UNION ALL
			SELECT LSTHDMX.SPDM, LSTHDMX.GG1DM, LSTHDMX.GG2DM, LSTHDMX.JE * -1 JE
			, LSTHDMX.SL * -1 SL
			FROM LSTHD JOIN LSTHDMX ON LSTHDMX.DJBH = LSTHD.DJBH
			WHERE  YS = '+1+' AND ' + @StratDate + ' AND ' + @EndDate + ' 
				AND LSTHD.DM1 = ' + @KHDaiMa  + ' 
			) A
			GROUP BY SPDM,GG1DM,GG2DM
		) LS ON KC.SPDM = LS.SPDM
			AND KC.GG1DM = LS.GG1DM 
			AND KC.GG2DM = LS.GG2DM  
		LEFT JOIN (SELECT SPDM, GG1DM, GG2DM, SUM(SL) KCSL, SUM(SL2) KCZTSL
			FROM SPKCB JOIN CANGKU ON SPKCB.CKDM = CANGKU.CKDM
			WHERE (SPKCB.SL<>0 OR SPKCB.SL2<>0) AND ( CANGKU.CKDM =  ' + @KHDaiMa  + ' )
			GROUP BY SPDM, GG1DM, GG2DM
			) DPKC ON KC.SPDM = DPKC.SPDM
			AND KC.GG1DM = DPKC.GG1DM 
			AND KC.GG2DM = DPKC.GG2DM  
		LEFT JOIN (SELECT SPDM, GG1DM, GG2DM, SUM(SL) KCSL, SUM(SL2) KCZTSL
			FROM SPKCB JOIN CANGKU ON SPKCB.CKDM = CANGKU.CKDM
			WHERE (SPKCB.SL<>0 OR SPKCB.SL2<>0) AND (CANGKU.CKDM = ' + @CKDaiMa  + ' )
			GROUP BY SPDM, GG1DM, GG2DM
			) CKKC ON KC.SPDM = CKKC.SPDM
			AND KC.GG1DM = CKKC.GG1DM 
			AND KC.GG2DM = CKKC.GG2DM ';
	
	execute(@sqlstr)  
	